closeGui: 'BARRIER'
pages: 'WRITABLE_BOOK'
inStock: 'LIME_STAINED_GLASS_PANE'
outOfStock: 'RED_STAINED_GLASS_PANE'
nextPageText: '&6Next Page ->'
previousPageText: '&6<- Previous Page'
goBackText: '&cGo Back To Item Search'
closeGuiText: '&cClose GUI'
itemSearchTitle: 'Item Search'
plotSearchTitle: 'Available Listings'
plotText: 'Plot: {location}'
noPlotFoundText: 'No plot found for this item'
adminPlotText: 'Admin Shop'
save_interval: 30
